
management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints: 
    web:  
      exposure:
        include: '*'


spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  profiles:
    active: dev
  