
management:
  endpoint:
    health:
      show-details: always
  endpoints: 
    web:  
      exposure:
        include: health, info , prometheus

spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  profiles:
    active: dev
  