server:
    port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epam
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
security:
  failure:
    count: 3
    duration: 300
  jwt:
     duration: 86400
     signing-key: epam-training-dev-rest-application-secretkey